### ISSUE TITLE
device-side assert triggered

### ISSUE THREAD

**Issue by edacgq** [yenchenlin/nerf-pytorch#11] opened 2020-08-17 08:56 UTC
Traceback (most recent call last):
  File "run_nerf.py", line 858, in <module>
    train()
  File "run_nerf.py", line 742, in train
    **render_kwargs_train)
  File "run_nerf.py", line 126, in render
    all_ret = batchify_rays(rays, chunk, **kwargs)
  File "run_nerf.py", line 59, in batchify_rays
    ret = render_rays(rays_flat[i:i+chunk], **kwargs)
  File "run_nerf.py", line 401, in render_rays
    raw = network_query_fn(pts, viewdirs, run_fn)
  File "run_nerf.py", line 204, in <lambda>
    netchunk=args.netchunk)
  File "run_nerf.py", line 49, in run_network
    outputs_flat = batchify(fn, netchunk)(embedded)
  File "run_nerf.py", line 33, in ret
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "run_nerf.py", line 33, in <listcomp>
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ovopark/nerf-pytorch-master/run_nerf_helpers.py", line 104, in forward
    h = F.relu(h)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 1119, in relu
    result = torch.relu(input)
RuntimeError: CUDA error: device-side assert triggered
➜  nerf-pytorch-master

**Comment by yenchenlin** [comment] 2020-09-09 02:45
May you provide the command that can reproduce the error?

**Comment by dunbar12138** [comment] 2020-10-23 17:18
Have you solved that problem? I meet the same problem when running 'python run_nerf.py --config configs/fern.txt'

**Comment by anilesec** [comment] 2020-12-14 14:51
> Have you solved that problem? I meet the same problem when running 'python run_nerf.py --config configs/fern.txt'

I also encountered the same problem. Did you find any solution?
I tried to debug, what I found is that values of tensor inds_g is too large and too small(which casuses out of bounds error)
inds_g.min()  = tensor(-4993021444723710459) 
inds_g.max() = tensor(4575432887736600530) 
inds_g = tensor([[[ 4255818524050935954,                   62],
         [ 4256250760978027750,                   62],
         [ 4237722774569238629,                   62],
         ...,]]
file "run_nerf_helpers.py"
cdf_g = torch.gather(cdf.unsqueeze(1).expand(matched_shape), 2, inds_g)

Best
Anil

**Comment by anilesec** [comment] 2020-12-14 14:53
> May you provide the command that can reproduce the error?

I get the same error, by just running the "python run_nerf.py --config configs/lego.txt"

**Comment by pgmsuper** [comment] 2020-12-23 08:39
I think you can try to upgrade your python's libraries, such as numpy and so on,I do that and succed run it

**Comment by yenchenlin** [comment] 2021-01-28 12:46
May I know which CUDA and PyTorch version you are using?

**Comment by yenchenlin** [comment] 2021-01-28 12:48
I am using CUDA 10.1

**Comment by yenchenlin** [comment] 2021-04-02 12:28
Closing due to no updated response ... feel free to bump it back if anything is wrong.

**Closed by yenchenlin** 2021-04-02 12:28 UTC

**Comment by domattioli** [comment] 2022-08-17 19:15
I'm using a [repo ](https://github.com/LemonATsu/A-NeRF) that is built off of NeRF and I am receiving the same error. Has anyone figured this out? I know I'm [not the only one](https://github.com/LemonATsu/A-NeRF/issues/9#issue-1162137263) with this issue on the A-NeRF forum. I'm wondering if it is a PyTorch issue?

CUDA: 11.3.1
PyTorch: 1.11.0
